#!/usr/local/bin/bash
echo $BREAKLINE

echo "${BBlue}${SPACER}"
echo "${BBlue}** Creating VIM folder's "
echo "${BBlue}${SPACERLINE}"

echo "${BGreen} mkdir -p ~/.vim/autoload"
mkdir -p ~/.vim/autoload

echo "${BGreen} mkdir -p ~/.vim/plugin"
mkdir -p ~/.vim/plugin

echo "${BGreen} mkdir -p ~/.vim/backups"
mkdir -p ~/.vim/tmp/backups

echo "${BBlue}${SPACERLINE}"
echo "${BBlue}** Finished creating VIM folder's "
echo "${BBlue}${SPACER}"

echo $BREAKLINE

echo "${BBlue}${SPACER}"
echo "${BBlue}** Downloading VIM Plug and Rename "
echo "${BBlue}${SPACERLINE}"

echo "${BGreen} curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim"
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

echo "${BGreen} curl --insecure -fLo ~/.vim/plugin/Rename.vim  http://www.vim.org/scripts/download_script.php?src_id=16331"
curl --insecure -fLo ~/.vim/plugin/Rename.vim  http://www.vim.org/scripts/download_script.php?src_id=16331 # vim plugin renamer :saveas
echo "${BBlue}${SPACERLINE}"
echo "${BBlue}** Finished downloading  VIM Plug and Rename "
echo "${BBlue}${SPACER}"