#!/usr/local/bin/bash

echo $BREAKLINE
echo "${BBlue}${SPACER}"
echo "${BBlue}** NPM Packages "
echo "${BBlue}${SPACERLINE}"


npmArray=( cordova ionic bower coffee-script yo gulp grunt-cli jshint browserify generator-webapp less sass 
typescript ios-sim ios-deploy electron-prebuilt azure-cli tslint  eslint )

for i in "${npmArray[@]}"
do
    echo "${BGreen}"
    read -e -p "Install ${i}? [y/N] (default to yes)" resp_node_${i/'-'/'_'}
    current_resp=resp_node_${i/'-'/'_'}
    current_resp=${!current_resp:-y}
    if [[ $current_resp =~ ^([yY]|[sS])$ ]]
    then        
        echo "${BGreen} +++ npm install -g ${i}"      
        npm install -g $i  
    fi
done

echo "${BBlue}${SPACERLINE}"
echo "${BBlue}** Finished NPM Packages "
echo "${BBlue}${SPACER}"