require("coder.plugins-setup")
require("coder.core.options")
require("coder.core.keymaps")
require("coder.core.colorscheme")

-- plugins
require("coder.plugins.project")
require("coder.plugins.comment")
require("coder.plugins.nvim-tree")
require("coder.plugins.lualine")
require("coder.plugins.nvim-cmp")
require("coder.plugins.lsp.mason")
require("coder.plugins.lsp.lspsaga")
require("coder.plugins.lsp.lspconfig")
require("coder.plugins.lsp.null-ls")
require("coder.plugins.autopairs")
require("coder.plugins.treesitter")
require("coder.plugins.gitsigns")
require("coder.plugins.nvim-terminal")
